name: Run Google Colab Notebook

on:
  schedule:
    - cron: '0 3 * * *'  # Lịch trình chạy mỗi ngày vào 10h sáng

jobs:
  run_colab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Colab Notebook
      run: |
        python connect_linkedin_with_cookie.py
