name: Run Google Colab Notebook

on:
  schedule:
    - cron: '0 4 * * *'  # Lịch trình chạy mỗi ngày vào 9h sáng UTC

jobs:
  run_colab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Colab Notebook
      run: |
        curl -X POST https://colab.research.google.com/drive/1kkw4HgAP_BLAfOpxNoZj-RCaYt53jVpR/execute
